### ISSUE TITLE
Heatmap: divergent color scale

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#1]
Change heatmap colors to better distinguished between up vs down-regulation of apoptotic
signals by drug treatments vs. medium control.

- Divergent color scale
- Two stars for higher significance

**Comment by deeenes** [comment]
[Here](https://github.com/saezlab/plugy/blob/8623beca25528508cd31eb9da3b493fc76e62591/plugy/data/config.py#L243). You can define two default continuous and two default diverging palettes. Continuous vs. diverging depends on whether the scale has a center (`heatmap_center_scale`). Alternatively, you can directly set the two cmaps (`heatmap_cmap`), the value provided there will be used no matter if the scale is centered.

**Comment by NgocHien-Du** [comment]
Got it.  Thanks!
