### ISSUE TITLE
Config: exclude conditions / drugs

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#10]
Give option to exclude certain drug treatments after the QC step

**Comment by deeenes** [comment]
Since [bf28e7b](https://github.com/saezlab/plugy/commit/bf28e7b0d923a9db459fd17f292f4bae13efa711) a list of sample or compound labels can be provided to the new config option `exclude`, and these samples will be discarded before running the quality control and analysis steps. If `exclude = ["Irinotecan", "Sorafenib"]`, all samples with either of these compounds will be discarded. If `exclude = "Irinotecan + Sorafenib", only the "Irinotecan + Sorafenib" combination is to be discarded. A full example:

```
import plugy

exp = plugy.PlugExperiment(
    heatmap_second_scale = 'pos_ctrl',
    figure_titles = False,
    exclude = "Irinotecan + Sorafenib",
)

exp.main()
```

[Here is how it works](https://github.com/saezlab/plugy/blob/8623beca25528508cd31eb9da3b493fc76e62591/plugy/data/plug.py#L1632).

The samples are discarded right after creating the `sample_df` data frame, before calculating the z-scores. If you decide about the samples after QC, you should initiate a new run or at least re-run the `samples` and `qc` steps of the workflow with the `exclude` option set.

**Comment by NgocHien-Du** [comment]
I guess the names of the drugs should match the ones in the channel file.

**Comment by deeenes** [comment]
Yes, it only works with the drug names used in the channel map. Does this solution cover all your use cases?

**Comment by NgocHien-Du** [comment]
Yes, it is. 
Just a confirmation: when we exclude a drug treatment in the analysis, the z-score calculation will be done without that sample.  Correct?

**Comment by deeenes** [comment]
Yes, [it is the first step](https://github.com/saezlab/plugy/blob/8623beca25528508cd31eb9da3b493fc76e62591/plugy/data/plug.py#L135) after creating the samples data frame, just before calculating z-scores

**Comment by NgocHien-Du** [comment]
thank you
