### ISSUE TITLE
Workflow management

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#11]
Give option to do the analysis in steps (currently all at once)

We should have this already, maybe it doesn't work, have to check

**Comment by deeenes** [comment]
Currently the workflow is divided into 5 parts:

- initialization (init)
- plug detection (plugs)
- sample detection (samples)
- quality control (qc)
- analysis (analysis)

These are executed according to the logic in [`PlugExperiment.main`](https://github.com/saezlab/plugy/blob/1e920669fea0b56a8419a922c6c5295298fa589e/plugy/exp.py#L121).

By default all of them are `None` and turned on based on other parameters. The user can override this by the config, or at the instantiation of `PlugExperiment` or when calling `main`. If the user turns on or off certain workflow steps, the prerequisites of the enabled steps will be enabled too. E.g. to run only the first 2 steps:

```
import plugy
exp = plugy.PlugExperiment()
exp.main(plugs = True)
```

Or detect the samples, but don't run quality control and analysis:

```
import plugy
exp = plugy.PlugExperiment()
exp.main(samples = True)
```

And so on. To run a single part, e.g. to run only `samples`:

```
exp._samples()
```

But it will fail if `init` and `plugs` have not been run already.

**Comment by NgocHien-Du** [comment]
Maybe there is already this function in the program.  However, there was no documentation so it would be great to have an example so that others can follow easily.

**Comment by deeenes** [comment]
In general, plugy has a ton of undocumented features, and where you can find most of the info is the [config](https://github.com/saezlab/plugy/blob/master/plugy/data/config.py). I recommend to read the comments in this file :)

Otherwise, I will soon set up an automated docs build and add some tutorials mostly from the examples I wrote in issues like this one.

Another question: do these parameters cover your case? If so, we can close this issue.

**Comment by NgocHien-Du** [comment]
I have tried to read the config file already.  But it is not easy for non-expert to find the relevant part and then to understand it.  I am improving but it would be great to have more tuitorials.  And the automated docs would be great too. 
Could you please give an example of how to run the 5 steps sequentially?

**Comment by NgocHien-Du** [comment]
Got it.  Thank you!
