### ISSUE TITLE
Heatmap of green signals

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#2]
Provide heatmap of green signals (currently only heatmap of green/orange signals)

**Comment by deeenes** [comment]
Heatmap of all channels + derived variables such as `readout / control` and `readout / control normalized to baseline control`. Heatmaps use divergent and centered color scale. Please let me know if it's alright:

![heatmap_matrix](https://user-images.githubusercontent.com/2679889/193825532-5029a26a-dcf2-49d9-9acf-7c17692e128d.png)

**Comment by NgocHien-Du** [comment]
Looks great.  Many thanks!
Btw, just a confirmation: what is 'Readout media norm'?

**Comment by deeenes** [comment]
`readout_media_norm` is a column name in the samples data frame, it contains the green:orange ratio after the drift of the medium only control was regressed out (that's what "media norm" is supposed to mean, sorry I didn't come up with these names :)
