### ISSUE TITLE
Channels → role mapping in config

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#3]
Modify the configuration step such that green/orange/uv signals can be switched on demand

**Comment by deeenes** [comment]
Currently the relevant part of the config [looks like this](https://github.com/saezlab/plugy/blob/1e920669fea0b56a8419a922c6c5295298fa589e/plugy/data/config.py#L102). Here one can set the column index, the color and the role of the fluorescent channels. I think the role is the stable reference, i.e. the code looks for the "barcode", "readout" or "control" channels. If from tomorrow the barcode is purple and is in column 0, the config can be:

```
{
    'barcode': ('purple', 0),
    'control': ('orange', 2),
    'readout': ('green', 1),
}
```

I am wondering if you meant something like this?

**Comment by NgocHien-Du** [comment]
We have tried to change the number of the column as you suggested but it didn't work. Sometimes we have 'uv' in column 2 and 'orange' in column 3, which is reserved of what is set now as default.  But swapping the number in the config didn't do anything.  I can try to find an example of a recording file to sent you if that helps.
