### ISSUE TITLE
More plug length figures

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#7]
In the QC folder, plot plug length for each drug treatment, by each cycle, and averaging all cycles

**Comment by deeenes** [comment]
What kind of plot? A grid of violins, boxplots, or densities?

**Comment by NgocHien-Du** [comment]
Boxplots or violinplot would be great.

**Comment by NgocHien-Du** [comment]
No, I want an extra figure with plug lengths for each sample.  The question is if the plug length for each sample are equal, or if there are some outliers.  We can use this information to check if the liquid are running well in the microfluidic for each channel.  So if some outliers are label, that would be great.  Can we also have a sum of the length of plugs for each sample?  Sometimes we would have smaller plugs for certain condition, but may be the sum of the length will be the same, which is still fine.

**Comment by deeenes** [comment]
Okay, now I understand. I added two new figures to the workflow, `length_by_sample` and `volume_by_sample`:

![length_by_sample](https://user-images.githubusercontent.com/2679889/194586815-605a8be3-20dc-40de-b81a-9ee35a429d7c.png)

**Comment by NgocHien-Du** [comment]
That is lovely.  Thanks!
