### ISSUE TITLE
y-axis limits for raw PMT data

### ISSUE THREAD

**Issue by deeenes** [saezlab/plugy#9]
Give option to plot pmt raw data with desired y-axis range.

I believe we have this already?

**Comment by deeenes** [comment]
Ok, I added this in the last figure revision, but forgot to commit it. Now `PlugExperiment.plot_pmt_data` has a `ymax` argument. `ymin` should be always zero, right?

**Comment by deeenes** [comment]
Just as an example, how we made the figures in the NP paper, Box 2 panel 1:

1) The usual workflow, creating the `PlugExperiment` instance, running `main`:

```
import plugy

figtype = 'svg'

exp = plugy.PlugExperiment(
    heatmap_second_scale = 'pos_ctrl',
    figure_titles = False,
    readout_analysis_column = 'readout_media_norm_z_score',
    heatmap_override_scale = (-1.1, 0.6),
    heatmap_override_second_scale = (-0.5, 4.25),
    figure_export_file_type = figtype,
    plot_git_caption = False,
)

exp.main()
```

2) Creating figure for the drug combination `Irinotecan + Sorafenib`, with setting the y-axis scale to 0.0-1.2 ("iri-sora" is a label to be used in the file name):

```
exp.plot_samples_cycles(
    samples = [
        'Irinotecan + Sorafenib'
    ],
    label = 'iri-sora',
    ymax = 1.2,
)
```

3) Creating SVG figure of raw data for a specified time interval (1668-1832):

```
exp.config.pmt_overview_force_png = False

exp.plot_pmt_data(
    width = 15,
    xmin = 1668,
    xmax = 1832,
    label = 'box2',
    ymax = 0.8,
)
```

Please let me know if this answers your requirements.

**Comment by NgocHien-Du** [comment]
Yes, it is. Thank you.
